name: Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: |
          cd applications/auth-service  # Entrando no diretório do microserviço
          go mod tidy  # Garantir que as dependências estão atualizadas

      - name: Build Go project
        run: |
          cd applications/auth-service  # Entrando no diretório do microserviço
          go build -v  # Faz o build do projeto
