name: Auth Service CI Pipeline

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Auth Service Code
        uses: actions/checkout@v3

      - name: Set up Go for Auth Service
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Install Dependencies for Auth Service
        run: |
          cd applications/auth-service
          go mod tidy

      - name: Build Auth Service Go Project
        run: |
          cd applications/auth-service
          go build -v