name: Continuous Integration
on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 20
      - name: Run install, build
        run: |
          cd frontend
          yarn install --force
          yarn run build